openapi: 3.0.1
info:
  title: AuthService
  description: API Definition of AuthService
  version: 1.0.0
servers:
- url: http://localhost:8290/auth
paths:
  /:
    post:
      responses:
        default:
          description: Default response
