openapi: 3.0.1
info:
  title: CartGetById
  description: API Definition of CartDelete
  version: 1.0.0
servers:
- url: http://localhost:8290/cart-getbyid
paths:
  /:
    get:
      responses:
        default:
          description: Default response
