openapi: 3.0.1
info:
  title: CartGetAll
  description: API Definition of CartGetById
  version: 1.0.0
servers:
- url: http://localhost:8290/cart-getall
paths:
  /:
    get:
      responses:
        default:
          description: Default response
