openapi: 3.0.1
info:
  title: CartUpdate
  description: API Definition of CartUpdate
  version: 1.0.0
servers:
- url: http://localhost:8290/cart-update
paths:
  /:
    put:
      responses:
        default:
          description: Default response
