openapi: 3.0.1
info:
  title: CategoryUpdate
  description: API Definition of CategoryUpdate
  version: 1.0.0
servers:
- url: http://localhost:8290/category-update
paths:
  /:
    put:
      responses:
        default:
          description: Default response
