openapi: 3.0.1
info:
  title: AccountConfirm
  description: API Definition of CategoryGetAll
  version: 1.0.0
servers:
- url: http://localhost:8290/accountConfirm
paths:
  /:
    get:
      responses:
        default:
          description: Default response
