openapi: 3.0.1
info:
  title: DeliveryGetByID
  description: API Definition of DeliveryGetByID
  version: 1.0.0
servers:
- url: http://localhost:8290/delevery-get-by-id
paths:
  /:
    get:
      responses:
        default:
          description: Default response
