openapi: 3.0.1
info:
  title: GetAllDelivery
  description: API Definition of GetAllDelivery
  version: 1.0.0
servers:
- url: http://localhost:8290/get-all-delivery
paths:
  /:
    get:
      responses:
        default:
          description: Default response
