openapi: 3.0.1
info:
  title: ItemGetAll
  description: API Definition of ItemGetAll
  version: 1.0.0
servers:
- url: http://localhost:8290/item-get-all
paths:
  /:
    get:
      responses:
        default:
          description: Default response
