openapi: 3.0.1
info:
  title: ItemDelete
  description: API Definition of ItemDelete
  version: 1.0.0
servers:
- url: http://localhost:8290/item-delete
paths:
  /:
    delete:
      responses:
        default:
          description: Default response
