openapi: 3.0.1
info:
  title: ResetPassword
  description: API Definition of ResetPassword
  version: 1.0.0
servers:
- url: http://localhost:8290/reset-passsowrd
paths:
  /:
    post:
      responses:
        default:
          description: Default response
