openapi: 3.0.1
info:
  title: UserCreate
  description: API Definition of UserCreate
  version: 1.0.0
servers:
- url: http://localhost:8290/create-user
paths:
  /:
    post:
      responses:
        default:
          description: Default response
